/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reallaundry;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static reallaundry.koneksi.getConnection;

/**
 *
 * @author Dzulkarnain Inc
 */
public class transaksi extends javax.swing.JFrame {

    koneksi db = new koneksi();
    Connection conn = getConnection();
    String cari = "";
    String brt = "";
    String total = "";
    String sumtotal = null;
    int hargatotal;
    private int id;

    /**
     * Creates new form transaksi
     */
    public transaksi(int id) {
        initComponents();
        setLocationRelativeTo(null);
        tableload(jTable1);
        kodeload(txnotransaksi);
        this.id = id;
        if(id == 0){
            insert.setVisible(false);
            printpdf.setVisible(false);
            update.setVisible(false);
        }else{
            insert.setVisible(true);
            printpdf.setVisible(true);
            update.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txnotransaksi = new javax.swing.JTextField();
        txidpegawai = new javax.swing.JTextField();
        txidpelanggan = new javax.swing.JTextField();
        txidjenis = new javax.swing.JTextField();
        txtanggal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        printpdf = new javax.swing.JButton();
        update = new javax.swing.JButton();
        cbberat = new javax.swing.JComboBox();
        txtotal = new javax.swing.JTextField();
        txbayar = new javax.swing.JTextField();
        txkembali = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txsearch = new javax.swing.JTextField();
        cbsearch = new javax.swing.JComboBox();
        insert1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "ID Pegawai", "ID Pelanggan", "ID Jenis", "Tanggal", "Berat", "Harga Total", "Pembayaran", "Kembalian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("No Transaksi");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("ID Pegawai");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("ID Pelanggan");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("ID Jenis");

        txnotransaksi.setEditable(false);
        txnotransaksi.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txidpegawai.setEditable(false);
        txidpegawai.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txidpelanggan.setEditable(false);
        txidpelanggan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txidjenis.setEditable(false);
        txidjenis.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        txtanggal.setEditable(false);
        txtanggal.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtanggal.setText("System Date");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Berat Cucian");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("Total Rp.");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel13.setText("Bayar Rp.");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setText("Kembali Rp.");

        insert.setBackground(new java.awt.Color(203, 203, 203));
        insert.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        printpdf.setBackground(new java.awt.Color(203, 203, 203));
        printpdf.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        printpdf.setText("Print");
        printpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printpdfActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(203, 203, 203));
        update.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        cbberat.setBackground(new java.awt.Color(203, 203, 203));
        cbberat.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cbberat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cbberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbberatActionPerformed(evt);
            }
        });

        txtotal.setEditable(false);
        txtotal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txbayar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbayarActionPerformed(evt);
            }
        });
        txbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbayarKeyPressed(evt);
            }
        });

        txkembali.setEditable(false);
        txkembali.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jButton2.setBackground(new java.awt.Color(203, 203, 203));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txsearch.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        cbsearch.setBackground(new java.awt.Color(203, 203, 203));
        cbsearch.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        cbsearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Transaksi", "ID Pegawai", "ID Pelanggan", "ID Jenis" }));
        cbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsearchActionPerformed(evt);
            }
        });

        insert1.setBackground(new java.awt.Color(203, 203, 203));
        insert1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        insert1.setText("Back");
        insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert1ActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(203, 203, 203));
        clear.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txsearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txnotransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txidjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txidpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbberat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtotal)
                                            .addComponent(txbayar)
                                            .addComponent(txkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(printpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(insert1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txnotransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txidpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txidjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbberat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        int kembali = 0;
        try {
            String sql = "INSERT INTO transaksi VALUES (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txnotransaksi.getText().trim());
            pst.setString(2, txidpegawai.getText().trim());
            pst.setString(3, txidpelanggan.getText().trim());
            pst.setString(4, txidjenis.getText().trim());
            pst.setDate(5, new java.sql.Date(System.currentTimeMillis()));
            pst.setString(6, cbberat.getSelectedItem().toString());
            pst.setString(7, txtotal.getText().trim());
            pst.setString(8, txbayar.getText().trim());
            kembali = Integer.parseInt(txbayar.getText()) - Integer.parseInt(sumtotal);
            pst.setInt(9, kembali);

            pst.execute();

            tableload(jTable1);
            clear();
            kodeload(txnotransaksi);
            JOptionPane.showMessageDialog(null, "Data Saved " + "\nKembalian : Rp." + kembali);

        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_insertActionPerformed

    private void printpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printpdfActionPerformed
        // TODO add your handling code here:
        if(jTextPane1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Select Transaksi","WARNING", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                jTextPane1.print();
            }catch(PrinterException e){
                JOptionPane.showMessageDialog(null, "ERROR !!");
                //Logger.getLogger(PrinterSys.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_printpdfActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int kembali = Integer.parseInt(txbayar.getText()) - Integer.parseInt(sumtotal);
        try {
            String sql = "UPDATE transaksi SET id_pegawai = "
            + txidpegawai.getText() + ", id_pelanggan = "
            + txidpelanggan.getText() + ", id_jenis = "
            + txidjenis.getText() + ", tanggal = sysdate, berat = "
            + cbberat.getSelectedItem().toString() + ", harga_total = "
            + txtotal.getText() + ", pembayaran = "
            + txbayar.getText() + ", kembalian = "
            + kembali + " WHERE no_transaksi = "
            + txnotransaksi.getText();

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();

            clear();
            tableload(jTable1);
            kodeload(txnotransaksi);

            JOptionPane.showMessageDialog(null, "Data Updated");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void cbberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbberatActionPerformed
        // TODO add your handling code here:
        total = cbberat.getSelectedItem().toString();
        if(total.equals("1")){
            try{
                String sql = "SELECT sum(harga * " + 1 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("2")){
            try{
                String sql = "SELECT sum(harga * " + 2 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("3")){
            try{
                String sql = "SELECT sum(harga * " + 3 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("4")){
            try{
                String sql = "SELECT sum(harga * " + 4 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("5")){
            try{
                String sql = "SELECT sum(harga * " + 5 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("6")){
            try{
                String sql = "SELECT sum(harga * " + 6 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("7")){
            try{
                String sql = "SELECT sum(harga * " + 7 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("8")){
            try{
                String sql = "SELECT sum(harga * " + 8 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }else if(total.equals("9")){
            try{
                String sql = "SELECT sum(harga * " + 9 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_cbberatActionPerformed

    private void txbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbayarActionPerformed

    private void txbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbayarKeyPressed
        // TODO add your handling code here:
        /*double tb = (Double) Double.parseDouble(txbayar.getText()) + (Double.parseDouble(txbayar.getText()) * 0.1);
        double tt = (Double) Double.parseDouble(sumtotal);
        System.out.println(tb + " - " + tt);
        double tk = tb - tt;
        txkembali.setText(String.valueOf(tk));*/
    }//GEN-LAST:event_txbayarKeyPressed

    private void cbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txnotransaksi.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        txidpegawai.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
        txidpelanggan.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        txidjenis.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        txtanggal.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
        cbberat.setSelectedItem(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5)));
        txtotal.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 6)));
        txbayar.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 7)));
        txkembali.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 8)));
        viewStruct();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cari = (String)cbsearch.getSelectedItem();
        if(cari == "No Transaksi"){
            search1(jTable1);
        }else if(cari == "ID Pegawai"){
            search2(jTable1);
        }else if(cari == "ID Pelanggan"){
            search3(jTable1);
        }else if(cari == "ID Jenis"){
            search4(jTable1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert1ActionPerformed
        // TODO add your handling code here:
        clear();
        if(txidpegawai.getText().equals("") || txidpegawai.getText().equals(String.valueOf(0))){
            new menu().setVisible(true);
            dispose();
        }else{
            new pelanggan(this.id).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_insert1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new transaksi().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbberat;
    private javax.swing.JComboBox cbsearch;
    private javax.swing.JButton clear;
    private javax.swing.JButton insert;
    private javax.swing.JButton insert1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton printpdf;
    private javax.swing.JTextField txbayar;
    public static javax.swing.JTextField txidjenis;
    public static javax.swing.JTextField txidpegawai;
    public static javax.swing.JTextField txidpelanggan;
    private javax.swing.JTextField txkembali;
    private javax.swing.JTextField txnotransaksi;
    private javax.swing.JTextField txsearch;
    private javax.swing.JTextField txtanggal;
    private javax.swing.JTextField txtotal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    
    private void tableload(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try { 
            ResultSet rset = db.getData("SELECT * FROM transaksi ORDER BY no_transaksi");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    
    private void kodeload(JTextField jText) {
        try {
            ResultSet rset = db.getData("SELECT max(no_transaksi) FROM transaksi");
            while(rset.next()){
                int i = rset.getInt(1);
                i += 1;
                jText.setText(String.valueOf(i));
            }
        } catch (Exception ex) {
            
        }
    }
    
    private void search1(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE no_transaksi LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    private void search2(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_pegawai LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    private void search3(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_pelanggan LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    private void search4(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_jenis LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }  
    
    private void clear(){
        kodeload(txnotransaksi);
        txidpegawai.setText(String.valueOf(this.id));
        txidpelanggan.setText("");
        txidjenis.setText("");
        txtanggal.setText("System Date");
        cbberat.setSelectedIndex(0);
        txtotal.setText("");
        txbayar.setText("");
        txkembali.setText("");
        txsearch.setText("");
        jTextPane1.setText("");
        
        tableload(jTable1);
    }
    
    private void viewStruct(){
        String jcu = "";
        String npel = "";
        try { 
            String sql = "SELECT nama_jenis FROM jenis_cucian WHERE id_jenis = " + txidjenis.getText();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while (rset.next()){
                jcu = rset.getString(1);
            }
        } catch (Exception ex) {
            
        }
        try { 
            String sql = "SELECT nama_pelanggan FROM pelanggan WHERE id_pelanggan = '" + txidpelanggan.getText() + "'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while (rset.next()){
                npel = rset.getString(1);
            }
        } catch (Exception ex) {
            
        }
        jTextPane1.setText(String.valueOf("\t       -- JOSS LAUNDRY -- \n " 
                + "            Jasa Layanan Cuci Kering Setrika Pakaian \n"
                + "         Jl.Semolowaru No.15 | 031-77175735 Surabaya \n"
                + " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n  No Transaksi \t : "
                + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + " \n  Tanggal \t\t : "
                + jTable1.getValueAt(jTable1.getSelectedRow(), 4) + " \n  Nama \t\t : "
                + npel + " \n  Jenis Cucian \t : "
                + jcu + " \n  Berat Cucian \t : " 
                + jTable1.getValueAt(jTable1.getSelectedRow(), 5) + " \n"
                + " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
                + "\n  Harga Total \t : Rp. "
                + jTable1.getValueAt(jTable1.getSelectedRow(), 6) + " \n"
                + "  Bayar \t\t : Rp. " + jTable1.getValueAt(jTable1.getSelectedRow(), 7) + " \n"
                + " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
                + " \n  *Kembalian \t\t : Rp. " + jTable1.getValueAt(jTable1.getSelectedRow(), 8) + " \n"
        ));
        
    }

}
